import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container mt-24 mx-auto px-12 py-4 w-4/5">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
